Repository Step3-kakao-tech-campus/Team12_FE, pull requests merged in 2023-11, with the labels that each got.

#71 [feat] : 계좌정보 입력 & 공고현황페이지 모킹 적용 및 코드 디버깅
  src/apis/index.js
  src/apis/register.js
  src/components/atoms/Card.jsx
  src/components/molecules/BankForm.jsx
  src/mocks/data/postListData.js
  src/mocks/data/registerData.js
  src/mocks/handlers/index.js
  src/mocks/handlers/postList.js
  src/mocks/handlers/register.js
  src/pages/PostListPage.jsx
  src/utils/alert.js
  src/utils/date.js
Labels: 🐞 bug, ✨ feature

#70 [feat]: 학생증 업로드, 공고상세페이지 수정
  src/App.js
  src/apis/myPage.js
  src/apis/post.js
  src/apis/postDetail.js
  src/apis/uploadCard.js
  src/components/atoms/Time.jsx
  src/components/organisms/Info.jsx
  src/components/organisms/Location.jsx
  src/components/organisms/PickerTime.jsx
  src/components/templates/AdminMyPage.jsx
  src/components/templates/GuestMyPage.jsx
  src/components/templates/MyPageTemplate.jsx
  src/components/templates/PickerMatch.jsx
  src/components/templates/PickerNoMatch.jsx
  src/components/templates/StudentMyPage.jsx
  src/components/templates/WriterMatch.jsx
  src/components/templates/WriterNoMatch.jsx
  src/constant/routes.js
  src/pages/PostDetailPage.jsx
  src/pages/UploadStudentCardPage.jsx
  src/utils/alert.js
Labels: ✨ feature

#72 [feat]: 공고 작성 페이지 수정 및 msw 테스트
  src/components/atoms/ErrorMsg.jsx
  src/components/atoms/Input.jsx
  src/components/atoms/RangeInput.jsx
  src/components/atoms/SelectInput.jsx
  src/components/atoms/TextArea.jsx
  src/components/templates/OrderDeadLine.jsx
  src/components/templates/OrderInfo.jsx
  src/components/templates/OrderRequest.jsx
  src/constant/postWrite/orderDeadLine.js
  src/constant/postWrite/orderInfo.js
  src/constant/postWrite/orderRequest.js
  src/constant/validateInputMsg.js
  src/mocks/handlers/index.js
  src/mocks/handlers/postWrite.js
  src/pages/PostWritePage.jsx
  src/utils/dateAndTime.js
Labels: 🐞 bug, ✨ feature

#74 [9주차] : 9주차 개발 코드 Merge
  package-lock.json
  package.json
  src/App.js
  src/apis/admin.js
  src/components/atoms/Info.jsx
  src/components/atoms/button/Button.jsx
  src/components/atoms/button/FilterBtn.jsx
  src/components/atoms/button/MinusBtn.jsx
  src/components/atoms/button/PlusBtn.jsx
  src/components/atoms/input/Input.jsx
  src/components/atoms/input/RangeInput.jsx
  src/components/atoms/input/SelectInput.jsx
  src/components/atoms/label/Label.jsx
  src/components/atoms/label/SubLabel.jsx
  src/components/atoms/nav/LoginNav.jsx
  src/components/atoms/nav/Nav.jsx
  src/components/atoms/nav/OtherNav.jsx
  src/components/layout/ProtectedRoute.jsx
  src/components/molecules/BankForm.jsx
  src/components/molecules/BtnNavigate.jsx
  src/components/molecules/CircleBtn.jsx
  src/components/molecules/FilterForm.jsx
  src/components/molecules/Labels.jsx
  src/components/organisms/AuthRequest.jsx
  src/components/organisms/PickerTime.jsx
  src/components/templates/MyPageTemplate.jsx
  src/components/templates/mypage/AdminMyPageTemplate.jsx
  src/components/templates/mypage/GuestMyPageTemplate.jsx
  src/components/templates/mypage/StudentMyPageTemplate.jsx
  src/components/templates/postDetail/PickerMatchTemplate.jsx
  src/components/templates/postDetail/PickerNoMatchTemplate.jsx
  src/components/templates/postDetail/WriterMatchTemplate.jsx
  src/components/templates/postDetail/WriterNoMatchTemplate.jsx
  src/components/templates/postWrite/OrderDeadLineTemplate.jsx
  src/components/templates/postWrite/OrderInfoTemplate.jsx
  src/components/templates/postWrite/OrderRequestTemplate.jsx
  src/constant/routes.js
  src/hooks/.keep
  src/mocks/handlers/admin.js
  src/pages/AdminAuthPage.jsx
  src/pages/AdminPage.jsx
  src/pages/ErrorPage.jsx
  src/pages/HomePage.jsx
  src/pages/LoginPage.jsx
  src/pages/PostDetailPage.jsx
  src/pages/PostListPage.jsx
  src/pages/PostWriteIntroPage.jsx
  src/pages/PostWritePage.jsx
  src/pages/RegisterBankPage.jsx
  src/pages/UploadStudentCardPage.jsx
  src/utils/alert.js
  src/utils/time.js
  tailwind.config.js
Labels: ✨ feature

#78 [feat] : 마이페이지 로그아웃 기능 추가 & 로그인 기능 설정 수정
  src/apis/index.js
  src/apis/login.js
  src/apis/register.js
  src/components/atoms/button/Button.jsx
  src/components/templates/MyPageTemplate.jsx
  src/constant/routes.js
  src/pages/KakaoOuathPage.jsx
  src/pages/LoginPage.jsx
  src/utils/alert.js
Labels: ✨ feature

#81 [feat] : 마이페이지 작성한 & 수락한 공고글 기능 개발
  src/App.js
  src/apis/post.js
  src/apis/postDetail.js
  src/components/molecules/MyPagePickupPostCards.jsx
  src/components/molecules/MyPageWritenPostCards.jsx
  src/components/templates/postDetail/WriterMatchTemplate.jsx
  src/constant/routes.js
  src/pages/LoginPage.jsx
  src/pages/MyPagePickupPostDetailPage.jsx
  src/pages/MyPageWritenPostDetailPage.jsx
  src/pages/PickupPostPage.jsx
  src/pages/WritenPostPage.jsx
Labels: 🐞 bug, ✨ feature

#82 [refactor & style] : 코드 삭제 및 CSS 조정
  src/App.js
  src/components/organisms/PickerTime.jsx
  src/components/templates/postDetail/PickerMatchTemplate.jsx
  src/components/templates/postDetail/PickerNoMatchTemplate.jsx
  src/constant/routes.js
  src/pages/KakaoOuathPage.jsx
  src/pages/mypage/AdminAuthPage.jsx
  src/pages/mypage/AdminPage.jsx
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/MyPagePickupPostDetailPage.jsx
  src/pages/mypage/MyPagePickupPostListPage.jsx
  src/pages/mypage/MyPageWritenPostDetailPage.jsx
  src/pages/mypage/MyPageWritenPostListPage.jsx
  src/pages/mypage/UploadStudentCardPage.jsx
Labels: ✨ feature

#84 [style & fix] : UI/UX 개선 작업 및 일부 버그 수정
  src/components/organisms/Location.jsx
  src/components/organisms/PickerTime.jsx
  src/components/templates/postDetail/PickerMatchTemplate.jsx
  src/components/templates/postDetail/PickerNoMatchTemplate.jsx
  src/components/templates/postDetail/WriterMatchTemplate.jsx
  src/components/templates/postDetail/WriterNoMatchTemplate.jsx
  src/pages/PostDetailPage.jsx
  src/pages/mypage/MyPageWritenPostDetailPage.jsx
  src/pages/mypage/UploadStudentCardPage.jsx
  src/utils/alert.js
Labels: ✨ feature

#86 [refactor] : 로그인 파트 로직 변경 & 변수 대문자로 변경
  .gitignore
  Dockerfile
  default.conf
  goorm.manifest
  k8s/deployment.yaml
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/service.yaml
  public/index.html
  src/apis/article.js
  src/components/layout/ProtectedRoute.jsx
  src/components/molecules/BankForm.jsx
  src/components/templates/MyPageTemplate.jsx
  src/mocks/data/loginData.js
  src/mocks/data/registerData.js
  src/mocks/handlers/index.js
  src/mocks/handlers/login.js
  src/mocks/handlers/register.js
  src/pages/KakaoOuathPage.jsx
  src/pages/LoginPage.jsx
  src/pages/mypage/MyPagePickupArticleListPage.jsx
  src/pages/mypage/MyPageWritenArticleListPage.jsx
Labels: ✨ feature

#87 [refactor] : DTO 변수명 반영 & index.js 수정
  src/apis/index.js
  src/apis/uploadCard.js
  src/components/molecules/Cards.jsx
  src/components/molecules/MyPagePickupArticleCards.jsx
  src/components/molecules/MyPageWritenArticleCards.jsx
  src/mocks/data/articleListData.js
  src/pages/ArticleWritePage.jsx
  src/pages/mypage/AdminAuthPage.jsx
  src/pages/mypage/MyPagePickupArticleListPage.jsx
  src/pages/mypage/MyPageWritenArticleListPage.jsx
Labels: ✨ feature

#88 [feat] : 관리자 페이지 작성 & 수락 공고글 탭 연결
  src/components/templates/mypage/AdminMyPageTemplate.jsx
Labels: ✨ feature

#90 fix: 공고 작성 관련 에러, 관리자 페이지 처리 로직 수정
  src/apis/admin.js
  src/apis/articleWrite.js
  src/components/templates/articleWrite/OrderDeadLineTemplate.jsx
  src/components/templates/articleWrite/OrderInfoTemplate.jsx
  src/constant/validateInputMsg.js
  src/constant/writeArticle.js
  src/mocks/data/adminData.js
  src/pages/ArticleWritePage.jsx
  src/pages/mypage/AdminAuthPage.jsx
  src/pages/mypage/AdminPage.jsx
  src/utils/alert.js
Labels: 🐞 bug, ✨ feature

#92 [fix & refactor] : 백엔드 API 연동 과정에서 변수 수정 & 버그 수정
  Dockerfile
  src/components/molecules/BankForm.jsx
  src/index.js
  src/pages/ArticleDetailPage.jsx
  src/pages/KakaoOuathPage.jsx
  src/pages/mypage/MyPagePickupArticleDetailPage.jsx
  src/pages/mypage/MyPagePickupArticleListPage.jsx
  src/pages/mypage/MyPageWritenArticleDetailPage.jsx
  src/pages/mypage/MyPageWritenArticleListPage.jsx
Labels: 🐞 bug, ✨ feature

#99 [fix] : 디버깅용 코드 수정
  src/apis/admin.js
  src/pages/ArticleListPage.jsx
Labels: ✨ feature

#101 [fix] : lastPage ~ ... pageable 추가
  src/pages/ArticleListPage.jsx
Labels: 🐞 bug

#102 [fix] : 공고상세페이지 isLoading 추가하여 렌더링 시도 & 관리자 페이지 디버깅
  src/apis/admin.js
  src/pages/ArticleDetailPage.jsx
  src/pages/ErrorPage.jsx
  src/pages/mypage/AdminAuthPage.jsx
  src/pages/mypage/AdminPage.jsx
  src/utils/alert.js
Labels: 🐞 bug

#103 [refactor] : 마이페이지 작성 및 수락 공고 목록 & 상세 페이지 코드 수정
  src/pages/mypage/MyPagePickupArticleDetailPage.jsx
  src/pages/mypage/MyPagePickupArticleListPage.jsx
  src/pages/mypage/MyPageWrittenArticleDetailPage.jsx
  src/pages/mypage/MyPageWrittenArticleListPage.jsx
Labels: 🐞 bug

#105 [fix] : 경로가 잘못 요청되는 버그, instance를 사용하지 않고 바로 axios사용하는 형태로 수정
  src/apis/admin.js
  src/apis/index.js
  src/apis/login.js
  src/apis/register.js
  src/components/templates/mypage/AdminMyPageTemplate.jsx
  src/pages/mypage/AdminAuthPage.jsx
  src/pages/mypage/AdminPage.jsx
Labels: 🐞 bug

#108 [fix] : mypage -> MYPAGE 상수로 변경
  src/components/templates/mypage/AdminMyPageTemplate.jsx
Labels: 🐞 bug

#109 [style]: 높이 깨지는 화면 변경
  src/global.css
  src/pages/ArticleListPage.jsx
  src/pages/HomePage.jsx
  src/pages/LoginPage.jsx
Labels: 🐞 bug

#110 fix: 공고상세 페이지 데이터 select 수정
  src/pages/ArticleDetailPage.jsx
  src/pages/mypage/UploadStudentCardPage.jsx
Labels: 🐞 bug

#111 [fix & conf] : Docker 파일 수정 및 API 요청 코드 파트 수정
  Dockerfile
  src/apis/index.js
  src/components/molecules/BankForm.jsx
  src/global.css
  src/pages/KakaoOuathPage.jsx
  src/pages/mypage/AdminAuthPage.jsx
  src/pages/mypage/AdminPage.jsx
  src/utils/occurError.js
Labels: 🐞 bug, ✨ feature

#113 [fix] : 디버깅 코드 수정(관리자페이지 쪽)
  src/pages/mypage/AdminPage.jsx
  src/pages/mypage/MyPageWrittenArticleListPage.jsx
Labels: 🐞 bug, ✨ feature

#115 [fix] : 상수 수정 & 수락한 공고글 코드 수정 & 관리자 인증 요청 목록 페이지 수정
  src/constant/mypage.js
  src/pages/ArticleListPage.jsx
  src/pages/mypage/AdminPage.jsx
  src/pages/mypage/MyPagePickupArticleListPage.jsx
Labels: 🐞 bug

#116 [fix] : 관리자 페이지 디버깅
  src/components/templates/mypage/StudentMyPageTemplate.jsx
  src/pages/mypage/AdminPage.jsx
  src/pages/mypage/MyPagePickupArticleListPage.jsx
Labels: 🐞 bug

#118 [fix] : 버그픽스
  src/App.js
  src/constant/error.js
  src/pages/mypage/AdminPage.jsx
  src/pages/mypage/MyPagePickupArticleListPage.jsx
Labels: 🐞 bug
