Repository Step3-kakao-tech-campus/Team12_FE, pull requests merged in 2023-10, with the labels that each got.

#17 [Feat]: Nav 컴포넌트 구현
  src/components/atoms/Nav.jsx
Labels: ✨ feature

#18 [style] : 페이지 레이아웃 box-sizing 추가 및 배경색 적용
  .eslintrc.json
  src/components/atoms/keep
  src/components/molecules/keep
  src/global.css
  src/pages/HomePage.jsx
  src/pages/KakaoOuathPage.jsx
  src/pages/LoginPage.jsx
  src/styles/.keep
  src/utils/.keep
Labels: ✨ feature

#19 [style] : HomePage Nav 추가 및 공고 작성 탭 경로 변경 & Nav 로고 수정
  src/assets/images/logo.png
  src/components/atoms/Nav.jsx
  src/pages/HomePage.jsx
Labels: ✨ feature

#20 [4주차] : 개발 사항 Merge
  .eslintrc.json
  .github/pull_request_template.md
  .gitignore
  .prettierrc.json
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/apis/.keep
  src/assets/.keep
  src/assets/images/kakao_login_medium_wide.png
  src/assets/images/logo.png
  src/components/atoms/Button.jsx
  src/components/atoms/Card.jsx
  src/components/atoms/Footer.jsx
  src/components/atoms/Input.jsx
  src/components/atoms/Label.jsx
  src/components/atoms/Loader.jsx
  src/components/atoms/Nav.jsx
  src/components/atoms/SelectInput.jsx
  src/components/atoms/SubLabel.jsx
  src/components/molecules/Labels.jsx
  src/components/organisms/.keep
  src/components/templates/.keep
  src/constant/bank.js
  src/constant/cafe.js
  src/global.css
  src/hooks/.keep
  src/index.js
  src/pages/HomePage.jsx
  src/pages/KakaoOuathPage.jsx
  src/pages/LoginPage.jsx
  src/pages/StartPostPage.jsx
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/Loader.css
  src/utils/alert.js
  src/utils/comma.js
  src/utils/date.js
  tailwind.config.js
Labels: ✨ feature

#21 [4주차] : 개발 사항 Merge(develop → master)
  .eslintrc.json
  .github/pull_request_template.md
  .gitignore
  .prettierrc.json
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/apis/.keep
  src/assets/.keep
  src/assets/images/kakao_login_medium_wide.png
  src/assets/images/logo.png
  src/components/atoms/Button.jsx
  src/components/atoms/Card.jsx
  src/components/atoms/Footer.jsx
  src/components/atoms/Input.jsx
  src/components/atoms/Label.jsx
  src/components/atoms/Loader.jsx
  src/components/atoms/Nav.jsx
  src/components/atoms/SelectInput.jsx
  src/components/atoms/SubLabel.jsx
  src/components/molecules/Labels.jsx
  src/components/organisms/.keep
  src/components/templates/.keep
  src/constant/bank.js
  src/constant/cafe.js
  src/global.css
  src/hooks/.keep
  src/index.js
  src/pages/HomePage.jsx
  src/pages/KakaoOuathPage.jsx
  src/pages/LoginPage.jsx
  src/pages/StartPostPage.jsx
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/Loader.css
  src/utils/alert.js
  src/utils/comma.js
  src/utils/date.js
  tailwind.config.js
Labels: ✨ feature

#23 [feat] : LoginNav 컴포넌트 구현
  src/apis/.keep
  src/components/atoms/LoginNav.jsx
  src/pages/LoginPage.jsx
Labels: ✨ feature

#25 [feat] : Card 컴포넌트 기능 보완
  package-lock.json
  package.json
  src/components/atoms/Card.jsx
  tailwind.config.js
Labels: ✨ feature

#26 [fix]: 버튼 컴포넌트로 변경
  src/pages/StartPostPage.jsx
Labels: ✨ feature

#28 [feat] : 메인페이지 구현
  src/App.js
  src/pages/HomePage.jsx
Labels: ✨ feature

#31 [feat] : 로그인 로직 추가 & 에러 페이지 추가
  src/App.js
  src/apis/index.js
  src/pages/ErrorPage.jsx
  src/pages/KakaoOuathPage.jsx
Labels: ✨ feature

#32 [feat]: 공고 작성 페이지 navigate 기능 구현
  src/App.js
  src/components/atoms/Input.jsx
  src/components/atoms/Line.jsx
  src/components/atoms/OtherNav.jsx
  src/components/molecules/BtnNavigate.jsx
  src/components/molecules/CircleBtn.jsx
  src/components/organisms/CircleNavigate.jsx
  src/components/templates/OrderDeadLine.jsx
  src/components/templates/OrderInfo.jsx
  src/components/templates/OrderRequest.jsx
  src/pages/PostWritePage.jsx
Labels: ✨ feature

#33 [feat] : 공고 현황 페이지 레이아웃 & 공고글 렌더링 구현
  src/App.js
  src/assets/images/postWrite.png
  src/components/atoms/ArticleNav.jsx
  src/components/molecules/Cards.jsx
  src/components/molecules/FilterForm.jsx
  src/global.css
  src/pages/PostListPage.jsx
Labels: ✨ feature

#37 [5주차] : 5주차 개발 코드 Merge 및 일부 리팩토링
  package-lock.json
  package.json
  src/App.js
  src/apis/index.js
  src/components/atoms/ArticleNav.jsx
  src/components/atoms/Button.jsx
  src/components/atoms/Nav.jsx
  src/components/atoms/OtherNav.jsx
  src/components/molecules/Cards.jsx
  src/components/organisms/.keep
  src/components/templates/.keep
  src/components/templates/MyPageTemplate.jsx
  src/pages/HomePage.jsx
  src/pages/KakaoOuathPage.jsx
  src/pages/MyPage.jsx
  src/pages/PostDetailPage.jsx
  src/pages/PostListPage.jsx
  src/pages/PostWriteIntroPage.jsx
  src/pages/StartPostPage.jsx
  src/utils/alert.js
Labels: ✨ feature

#38 [5주차] : 개발 사항 Merge(weekly-5 → develop)
  package-lock.json
  package.json
  src/App.js
  src/apis/.keep
  src/apis/index.js
  src/assets/images/postWrite.png
  src/components/atoms/Button.jsx
  src/components/atoms/Card.jsx
  src/components/atoms/Input.jsx
  src/components/atoms/Line.jsx
  src/components/atoms/LoginNav.jsx
  src/components/atoms/MinusBtn.jsx
  src/components/atoms/Nav.jsx
  src/components/atoms/OtherNav.jsx
  src/components/atoms/PlusBtn.jsx
  src/components/atoms/SelectInput.jsx
  src/components/atoms/TextArea.jsx
  src/components/molecules/BtnNavigate.jsx
  src/components/molecules/Cards.jsx
  src/components/molecules/CircleBtn.jsx
  src/components/molecules/FilterForm.jsx
  src/components/molecules/PlusMinusBtn.jsx
  src/components/organisms/.keep
  src/components/organisms/CircleNavigate.jsx
  src/components/templates/.keep
  src/components/templates/MyPageTemplate.jsx
  src/components/templates/OrderDeadLine.jsx
  src/components/templates/OrderInfo.jsx
  src/components/templates/OrderRequest.jsx
  src/global.css
  src/pages/ErrorPage.jsx
  src/pages/HomePage.jsx
  src/pages/KakaoOuathPage.jsx
  src/pages/LoginPage.jsx
  src/pages/MyPage.jsx
  src/pages/PostDetailPage.jsx
  src/pages/PostListPage.jsx
  src/pages/PostWriteIntroPage.jsx
  src/pages/PostWritePage.jsx
  src/pages/StartPostPage.jsx
  src/utils/alert.js
  tailwind.config.js
Labels: ✨ feature

#39 [5주차] : 개발 사항 Merge(develop → master)
  package-lock.json
  package.json
  src/App.js
  src/apis/.keep
  src/apis/index.js
  src/assets/images/postWrite.png
  src/components/atoms/Button.jsx
  src/components/atoms/Card.jsx
  src/components/atoms/Input.jsx
  src/components/atoms/Line.jsx
  src/components/atoms/LoginNav.jsx
  src/components/atoms/MinusBtn.jsx
  src/components/atoms/Nav.jsx
  src/components/atoms/OtherNav.jsx
  src/components/atoms/PlusBtn.jsx
  src/components/atoms/SelectInput.jsx
  src/components/atoms/TextArea.jsx
  src/components/molecules/BtnNavigate.jsx
  src/components/molecules/Cards.jsx
  src/components/molecules/CircleBtn.jsx
  src/components/molecules/FilterForm.jsx
  src/components/molecules/PlusMinusBtn.jsx
  src/components/organisms/.keep
  src/components/organisms/CircleNavigate.jsx
  src/components/templates/.keep
  src/components/templates/MyPageTemplate.jsx
  src/components/templates/OrderDeadLine.jsx
  src/components/templates/OrderInfo.jsx
  src/components/templates/OrderRequest.jsx
  src/global.css
  src/pages/ErrorPage.jsx
  src/pages/HomePage.jsx
  src/pages/KakaoOuathPage.jsx
  src/pages/LoginPage.jsx
  src/pages/MyPage.jsx
  src/pages/PostDetailPage.jsx
  src/pages/PostListPage.jsx
  src/pages/PostWriteIntroPage.jsx
  src/pages/PostWritePage.jsx
  src/pages/StartPostPage.jsx
  src/utils/alert.js
  tailwind.config.js
Labels: ✨ feature

#40 전남대_12조_픽업셔틀_5주차
  package-lock.json
  package.json
  src/App.js
  src/apis/.keep
  src/apis/index.js
  src/assets/images/postWrite.png
  src/components/atoms/Button.jsx
  src/components/atoms/Card.jsx
  src/components/atoms/Input.jsx
  src/components/atoms/Line.jsx
  src/components/atoms/LoginNav.jsx
  src/components/atoms/MinusBtn.jsx
  src/components/atoms/Nav.jsx
  src/components/atoms/OtherNav.jsx
  src/components/atoms/PlusBtn.jsx
  src/components/atoms/SelectInput.jsx
  src/components/atoms/TextArea.jsx
  src/components/molecules/BtnNavigate.jsx
  src/components/molecules/Cards.jsx
  src/components/molecules/CircleBtn.jsx
  src/components/molecules/FilterForm.jsx
  src/components/molecules/PlusMinusBtn.jsx
  src/components/organisms/.keep
  src/components/organisms/CircleNavigate.jsx
  src/components/templates/.keep
  src/components/templates/MyPageTemplate.jsx
  src/components/templates/OrderDeadLine.jsx
  src/components/templates/OrderInfo.jsx
  src/components/templates/OrderRequest.jsx
  src/global.css
  src/pages/ErrorPage.jsx
  src/pages/HomePage.jsx
  src/pages/KakaoOuathPage.jsx
  src/pages/LoginPage.jsx
  src/pages/MyPage.jsx
  src/pages/PostDetailPage.jsx
  src/pages/PostListPage.jsx
  src/pages/PostWriteIntroPage.jsx
  src/pages/PostWritePage.jsx
  src/pages/StartPostPage.jsx
  src/utils/alert.js
  tailwind.config.js
Labels: 🙋‍♂️ Request Review

#42 [style] : 공고글 매칭완료 문구 배치 수정
  src/components/atoms/Card.jsx
Labels: ✨ feature

#43 [feat] : 공고 현황 페이지 공고글 필터링 기능 & 무한스크롤 기능 구현
  package-lock.json
  package.json
  src/apis/index.js
  src/apis/post.js
  src/components/atoms/FilterBtn.jsx
  src/components/molecules/Cards.jsx
  src/components/molecules/FilterForm.jsx
  src/index.js
  src/pages/PostListPage.jsx
Labels: ✨ feature

#46 [feat] : 공고상세페이지 작성자용 구현
  src/App.js
  src/pages/PostDetailWriterPage.jsx
Labels: ✨ feature

#44 [feat]: 공고 작성 페이지 기본적인 ui 및 로직 구현
  src/components/atoms/Input.jsx
  src/components/atoms/Label.jsx
  src/components/atoms/RangeInput.jsx
  src/components/atoms/SelectInput.jsx
  src/components/atoms/TextArea.jsx
  src/components/templates/OrderInfo.jsx
  src/components/templates/OrderRequest.jsx
  src/constant/price.js
  src/routes.js
  src/styles/thumb.css
Labels: ✨ feature

#54 [feat]: 공고 작성 페이지 버그 수정
  package-lock.json
  package.json
  public/index.html
  src/components/templates/OrderInfo.jsx
  src/components/templates/OrderRequest.jsx
Labels: 🐞 bug

#56 [feat] : 로그인 로직 보완 & 로그인 및 접근권한 체크용 ProtectedRoute 컴포넌트 구현
  .eslintrc.json
  src/App.js
  src/components/templates/ProtectedRoute.jsx
  src/pages/KakaoOuathPage.jsx
  src/pages/MyPage.jsx
  src/utils/alert.js
Labels: ✨ feature

#59 [7주차] : 개발 사항 Merge(weekly-7 → develop)
  .eslintrc.json
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/templates/OrderInfo.jsx
  src/components/templates/OrderRequest.jsx
  src/components/templates/ProtectedRoute.jsx
  src/pages/KakaoOuathPage.jsx
  src/pages/MyPage.jsx
  src/utils/alert.js
Labels: ✨ feature

#60 [7주차] : 개발 사항 Merge(develop → master)
  .eslintrc.json
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/templates/OrderInfo.jsx
  src/components/templates/OrderRequest.jsx
  src/components/templates/ProtectedRoute.jsx
  src/pages/KakaoOuathPage.jsx
  src/pages/MyPage.jsx
  src/utils/alert.js
Labels: ✨ feature

#57 [feat] : 공고상세페이지 분기, 마이페이지
  src/App.js
  src/apis/postDetail.js
  src/components/organisms/Info.jsx
  src/components/organisms/Location.jsx
  src/components/organisms/PickerTime.jsx
  src/components/templates/AdminMyPage.jsx
  src/components/templates/GuestMyPage.jsx
  src/components/templates/MyPageTemplate.jsx
  src/components/templates/PickerMatch.jsx
  src/components/templates/PickerNoMatch.jsx
  src/components/templates/StudentMyPage.jsx
  src/components/templates/WriterMatch.jsx
  src/components/templates/WriterNoMatch.jsx
  src/pages/PostDetailPage.jsx
  src/pages/PostDetailWriterPage.jsx
  src/styles/DeleteSpin.css
Labels: ✨ feature

#64 [feat] : 로그인(회원가입) 페이지 - 계좌정보 입력 페이지 구현
  src/App.js
  src/apis/register.js
  src/components/molecules/BankForm.jsx
  src/constant/bank.js
  src/constant/routes.js
  src/pages/RegisterBankPage.jsx
  src/utils/alert.js
Labels: ✨ feature

#63 [feat]: 관리자 페이지, 관리자 상세 페이지, 공고 작성 페이지
  .eslintrc.json
  package.json
  public/mockServiceWorker.js
  src/App.js
  src/components/atoms/MinusBtn.jsx
  src/components/organisms/AuthDetail.jsx
  src/components/organisms/AuthRequest.jsx
  src/constant/routes.js
  src/index.js
  src/mocks/browser.js
  src/mocks/data/adminData.js
  src/mocks/handlers/admin.js
  src/mocks/handlers/index.js
  src/pages/AdminAuthPage.jsx
  src/pages/AdminPage.jsx
  src/pages/PostWritePage.jsx
  src/utils/alert.js
Labels: ✨ feature

#66 [8주차] : 8주차 개발 코드 Merge
  package-lock.json
  src/App.js
Labels: ✨ feature

#67 [8주차] : 개발 사항 Merge(weekly-8 → develop)
  .eslintrc.json
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.js
  src/apis/postDetail.js
  src/apis/register.js
  src/components/atoms/MinusBtn.jsx
  src/components/molecules/BankForm.jsx
  src/components/organisms/AuthDetail.jsx
  src/components/organisms/AuthRequest.jsx
  src/components/organisms/Info.jsx
  src/components/organisms/Location.jsx
  src/components/organisms/PickerTime.jsx
  src/components/templates/AdminMyPage.jsx
  src/components/templates/GuestMyPage.jsx
  src/components/templates/MyPageTemplate.jsx
  src/components/templates/PickerMatch.jsx
  src/components/templates/PickerNoMatch.jsx
  src/components/templates/StudentMyPage.jsx
  src/components/templates/WriterMatch.jsx
  src/components/templates/WriterNoMatch.jsx
  src/constant/bank.js
  src/constant/routes.js
  src/index.js
  src/mocks/browser.js
  src/mocks/data/adminData.js
  src/mocks/handlers/admin.js
  src/mocks/handlers/index.js
  src/pages/AdminAuthPage.jsx
  src/pages/AdminPage.jsx
  src/pages/PostDetailPage.jsx
  src/pages/PostDetailWriterPage.jsx
  src/pages/PostWritePage.jsx
  src/pages/RegisterBankPage.jsx
  src/styles/DeleteSpin.css
  src/utils/alert.js
Labels: ✨ feature

#68 [8주차] : 개발 사항 Merge(develop → master)
  .eslintrc.json
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.js
  src/apis/postDetail.js
  src/apis/register.js
  src/components/atoms/MinusBtn.jsx
  src/components/molecules/BankForm.jsx
  src/components/organisms/AuthDetail.jsx
  src/components/organisms/AuthRequest.jsx
  src/components/organisms/Info.jsx
  src/components/organisms/Location.jsx
  src/components/organisms/PickerTime.jsx
  src/components/templates/AdminMyPage.jsx
  src/components/templates/GuestMyPage.jsx
  src/components/templates/MyPageTemplate.jsx
  src/components/templates/PickerMatch.jsx
  src/components/templates/PickerNoMatch.jsx
  src/components/templates/StudentMyPage.jsx
  src/components/templates/WriterMatch.jsx
  src/components/templates/WriterNoMatch.jsx
  src/constant/bank.js
  src/constant/routes.js
  src/index.js
  src/mocks/browser.js
  src/mocks/data/adminData.js
  src/mocks/handlers/admin.js
  src/mocks/handlers/index.js
  src/pages/AdminAuthPage.jsx
  src/pages/AdminPage.jsx
  src/pages/PostDetailPage.jsx
  src/pages/PostDetailWriterPage.jsx
  src/pages/PostWritePage.jsx
  src/pages/RegisterBankPage.jsx
  src/styles/DeleteSpin.css
  src/utils/alert.js
Labels: ✨ feature
